services:
  postgres:
    container_name: pg-estore-db-cn
    image: postgres
    #env_file: /variables.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=pg-estore-db
    ports:
      - 5432:5432
    volumes:
      - postgres-estore-data:/data

  dotnet-estore:
    image: grsse/dotnet-estore:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=pg-estore-db-cn;Port=5432;User Id=postgres;Password=postgrespw;Database=pg-estore-db
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres-estore-data:
