# fly.toml app configuration file generated for artstore on 2023-10-27T21:06:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "artstore"
primary_region = "lhr"

[build]
  image = "grsse/artstore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__ApiKey = "621877894579812"
  CloudinarySettings__CloudName = "kw9xdfo024q"
  StripeSettings__PublishableKey = "pk_test_51O5wZRA2iJFRP1Pu4qP2JSqI1Sg1Sdt7tHj8EkrrPaIhDy2D2gfsN5oNKC6wTybyFwoiDGjIzVEgasJenAbXoL5g00LTl9btCE"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"